regex_detector:
  enabled: true
  rules:
    - name: "Private Key (RSA)"
      kind: "Private Key"
      pattern: '-----BEGIN RSA PRIVATE KEY-----'
      redact: true

    - name: "Private Key (EC)"
      kind: "Private Key"
      pattern: '-----BEGIN EC PRIVATE KEY-----'
      redact: true

    - name: "AWS Access Key"
      kind: "AWS Access Key"
      # word-boundary + AKIA + 16 uppercase/digits
      pattern: '\b(AKIA[0-9A-Z]{15,20})\b'
      redact: true

    - name: "Generic API Key"
      kind: "Generic API Key"
      # (?i) inline flag MUST be single-quoted and backslashes escaped for YAML
      pattern: '(?i)\b(api_?key|token|secret)[:=]\s*([A-Za-z0-9_\-]{16,})\b'
      redact: true

    - name: "GitHub Token (classic-ish)"
      kind: "GitHub Token"
      pattern: '\b(gh[pous]_[A-Za-z0-9]{20,})\b'
      redact: true

    - name: "Slack Webhook"
      kind: "Slack Webhook"
      pattern: 'https://hooks\.slack\.com/services/[A-Z0-9]{9}/[A-Z0-9]{9}/[A-Za-z0-9]{24}'
      redact: true

# Legacy style configuration used by older tests
detectors:
  - type: regex
    name: "AWS Access Key"
    kind: "AWS Access Key"
    pattern: '\b(AKIA[0-9A-Z]{15,20})\b'
    redact: true
