# Global scanning knobs (CI and local)
include_globs:
  - "**/*"

exclude_globs:
  - "**/.git/**"
  - "**/.venv/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.pytest_cache/**"
  - "**/__pycache__/**"
  # Add project-specific noisy paths here:
  - "docs/**"
  - "examples/**"

min_match_length: 8           # simple noise gate for very short matches
confidence_threshold: 0.0     # reserved (for ML detectors later)

# Optional: turn detectors on/off by 'name'
disabled_detectors:
  # - "Generic API Key"
  # - "Private Key (RSA)"
