[project]
name = "secret-scan-360"
version = "0.0.1"
requires-python = ">=3.10"
description = "Secret Scan 360"
dependencies = ["pyyaml", "requests"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
