[project]
name = "secret-scan-360"
version = "0.0.0"
requires-python = ">=3.10"
description = "Secret Scan 360 (work-in-progress)"
dependencies = [
  "PyYAML>=6.0.1",
  "requests>=2.31.0",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
include = ["services*", "detectors*"]
exclude = ["tests*", "ops*", "agents*"]
