# Auto-generated by SS360 Dev Agent
import re
from typing import Iterable, Dict, Iterator


# Simple first-cut regex. You can refine via spec if needed.
PATTERN = re.compile(r"https://hooks\.slack\.com/services/[A-Z0-9]{9}/[A-Z0-9]{9}/[A-Za-z0-9]{24}")


def detect(lines: Iterable[str]) -> Iterator[Dict[str, object]]:
    """
    Yield findings with line numbers when pattern matches.
    """
    for i, line in enumerate(lines, start=1):
        if PATTERN.search(line):
            yield {
                "id": "cli_baseline",
                "title": "CLI Baseline + Formats",
                "severity": "high",
                "description": "Sensitive value detected",
                "line": i,
            }
