# Auto-generated by SS360 Dev Agent
import re
from typing import Iterable, List
from ss360.core.findings import Finding

NAME = "slack_webhook"
SEVERITY = "high"

PATTERN = re.compile(
    r"https://hooks\.slack\.com/services/[A-Z0-9]{9}/[A-Z0-9]{9}/[A-Za-z0-9]{24}"
)


def scan(blob: bytes, path: str) -> List[Finding]:
    """New detector interface using Finding objects."""
    text = blob.decode(errors="ignore")
    findings = []
    
    for line_num, line in enumerate(text.splitlines(), start=1):
        for match in PATTERN.finditer(line):
            url = match.group(0)
            # Redact the webhook URL - show domain and truncate the rest
            hint = "https://hooks.slack.com/services/[REDACTED]"
            
            findings.append(
                Finding.from_match(
                    rule=NAME,
                    path=path,
                    line=line_num,
                    match_hint=hint,
                    severity=SEVERITY,
                    reason="Slack incoming webhook URL detected",
                )
            )
    return findings


def detect(lines: Iterable[str]):
    for i, line in enumerate(lines, start=1):
        if PATTERN.search(line):
            yield {
                "id": "slack_webhook",
                "title": "Slack Webhook Detector",
                "severity": "high",
                "description": "Slack incoming webhook URL detected",
                "line": i,
            }
