
name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install api deps
        run: |
          pip install -r services/api/requirements.txt
      - name: Lint (basic)
        run: |
          python -m pyflakes services/api/app || true
      - name: Validate schema file present
        run: |
          test -f sql_init.sql
