name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -U pip
      - run: pip install -e .
      - run: pip install black flake8 pyyaml
      - name: Black (format)
        run: black .
      - name: Flake8 (lint)
        run: flake8 .
      - name: Run SS360 scan (PR)
        if: always()
        run: |
          # Run scan with network disabled (safe for CI)
          python -m ss360.cli scan src --policy policy.example.yml --format json --json-out findings.json --sarif-out findings.sarif
          echo "Scan completed with exit code: $?"

      - name: Upload SARIF results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: findings.sarif
          category: ss360-secrets
      - name: Upload scan results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ss360-scan-results
          path: |
            findings.json
            findings.sarif
      - name: Tests required if code changed
        if: always()
        run: python scripts/require_tests_changed.py
