name: CI

on:
  push:
    branches: [ main, 'agent/*', 'feat-*' ]
  pull_request:
  workflow_dispatch:
    inputs:
      run_agent:
        description: "Run the dev agent tasks"
        required: false
        default: "false"

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install project deps
        run: |
          python -m pip install --upgrade pip
          # Core app deps (api/agents services)
          if [ -f services/api/requirements.txt ]; then pip install -r services/api/requirements.txt; fi
          if [ -f services/agents/requirements.txt ]; then pip install -r services/agents/requirements.txt; fi
          # Dev tooling
          pip install -r agents/dev/requirements.txt || true
          pip install pytest pre-commit

      - name: Pre-commit (lint/format)
        run: pre-commit run --all-files

      - name: Run unit tests
        env:
          PYTHONPATH: .
        run: |
          pytest -q

  dev_agent:
    if: >
      github.event_name == 'workflow_dispatch' && github.event.inputs.run_agent == 'true'
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install agent deps
        run: |
          python -m pip install --upgrade pip
          pip install -r agents/dev/requirements.txt || true
          # Fallback if that file changes
          pip install "crewai>=0.30.0" "openai>=1.30.0" "python-dotenv>=1.0.1"

      - name: Run dev agent
        run: |
          python agents/dev/run_agent_impl.py

