name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -U pip
      - run: pip install -e .
      - run: pip install black flake8 pyyaml
      - name: Black (format)
        run: black .
      - name: Flake8 (lint)
        run: flake8 .
      - name: SS360 scan
        run: python scripts/ci_scan.py --json-out findings.json --root .
      - name: Tests required if code changed
        run: python scripts/require_tests_changed.py
      - name: Notify agents (always)
        if: always()
        env:
          WEBHOOK: ${{ secrets.AGENTS_WEBHOOK_URL }}
          TOKEN:   ${{ secrets.AGENTS_WEBHOOK_TOKEN }}
          JOB_STATUS: ${{ job.status }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_JOB: ${{ github.job }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.head_ref || github.ref_name }}
          PR_NUMBER: ${{ github.event.pull_request.number || '' }}
        run: python scripts/notify_hub.py
