name: CI
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -U pip
      - run: pip install -e .
      - run: pip install black flake8 pyyaml
      - name: Black (format)
        run: black .
      - name: Flake8 (lint)
        run: flake8 .
      - name: SS360 scan
        run: python scripts/ci_scan.py --json-out findings.json --root .
      - name: Tests required if code changed
        run: python scripts/require_tests_changed.py
      - name: Notify agents (always)
        if: always()
        env:
          WEBHOOK: ${{ secrets.AGENTS_WEBHOOK_URL }}
          TOKEN:   ${{ secrets.AGENTS_WEBHOOK_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${WEBHOOK:-}" ]; then
            status="${{ job.status }}"
            sev=$([ "$status" = "success" ] && echo low || echo high)
            run_id="${{ github.run_id }}"
            job="build"
            repo="${{ github.repository }}"
            branch="${{ github.head_ref || github.ref_name }}"
            pr="${{ github.event.pull_request.number || 0 }}"
            cat > payload.json <<EOF
            {"event":"finding.${sev}","repo":"${repo}","job_id":"gha-${run_id}","finding_id":"gha-${run_id}-${job}","file_path":".github/workflows/ci.yml","detector_id":"gha_status","severity":"${sev}","recommendation":"CI job ${job} is ${status} on ${branch} (PR #${pr})"}
            EOF
            curl -sS -X POST "$WEBHOOK"               -H "Content-Type: application/json"               -H "X-Agent-Token: ${TOKEN:-}"               --data-binary @payload.json
          fi
