name: CI
on:
  pull_request:
jobs:
  lint_and_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -U pip
      - run: pip install -e .
      - run: pip install pre-commit black flake8
      - run: pre-commit run --all-files --show-diff-on-failure
      - run: ss360 --version
      - run: ss360 scan --json-out findings.json .

      - name: Notify agents (always)
        if: always()
        env:
          WEBHOOK: ${{ secrets.AGENTS_WEBHOOK_URL }}
          TOKEN:   ${{ secrets.AGENTS_WEBHOOK_TOKEN }}
        run: |
          if [ -n "$WEBHOOK" ]; then
            curl -sS -X POST "$WEBHOOK" \
              -H "Content-Type: application/json" \
              -H "X-Agent-Token: $TOKEN" \
              -d @- <<JSON
            {"event":"gha.status",
             "repo":"${{ github.repository }}",
             "branch":"${{ github.head_ref || github.ref_name }}",
             "pr_number":${{ github.event.pull_request.number || 0 }},
             "status":"${{ job.status }}",
             "job":"lint_and_scan"}
            JSON
          fi

