name: CI
on:
  pull_request:
jobs:
  lint_and_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -U pip
      - run: pip install -e .
      - run: pip install black flake8 pyyaml
      - name: Black (format)
        run: black .
      - name: Flake8 (lint)
        run: flake8 .
      - name: SS360 scan
        run: python scripts/ci_scan.py --json-out findings.json .

      - name: Notify agents (always)
        if: always()
        shell: bash
        env:
          WEBHOOK: ${{ secrets.AGENTS_WEBHOOK_URL }}
          TOKEN:   ${{ secrets.AGENTS_WEBHOOK_TOKEN }}
          RUN_ID:  ${{ github.run_id }}
          JOB:     lint_and_scan
          REPO:    ${{ github.repository }}
          BRANCH:  ${{ github.head_ref || github.ref_name }}
          PR:      ${{ github.event.pull_request.number || '' }}
          STATUS:  ${{ job.status }}
        run: |
          set -euo pipefail
          if [[ -n "${WEBHOOK:-}" && -n "${TOKEN:-}" ]]; then
            [[ "$STATUS" == "success" ]] && sev=low || sev=high
            json=$(printf '%s' \
              '{"event":"finding.'"$sev"'","repo":"'"$REPO"'","job_id":"gha-'"$RUN_ID"'",'\
              '"finding_id":"gha-'"$RUN_ID"'-'"$JOB"'","file_path":".github/workflows/ci.yml",'\
              '"detector_id":"gha_status","severity":"'"$sev"'","recommendation":'\
              '"CI job '"$JOB"' is '"$STATUS"' on '"$BRANCH"' (PR #'"$PR"')"}')
            curl -sS -X POST "$WEBHOOK" \
              -H "Content-Type: application/json" \
              -H "X-Agent-Token: $TOKEN" \
              -d "$json"
          else
            echo "WEBHOOK/TOKEN not set, skipping notify."
          fi
