name: Notify Agents on CI Failure
on:
  workflow_run:
    workflows: ["CI (lint)"]
    types: [completed]
jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: POST to agent-hub
        env:
          AGENTS_WEBHOOK_URL: ${{ secrets.AGENTS_WEBHOOK_URL }}
        run: |
          pr_number="$(jq -r '.[0].number // empty' <<< "${{ toJson(github.event.workflow_run.pull_requests) }}")"
          curl -sS -X POST "$AGENTS_WEBHOOK_URL" -H 'Content-Type: application/json' -d @- <<JSON
          {
            "event": "ci.failed",
            "repo": "${{ github.repository }}",
            "pr": "$pr_number",
            "workflow": "${{ github.event.workflow_run.name }}",
            "run_id": "${{ github.event.workflow_run.id }}"
          }
          JSON
