name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install build dependencies
        run: |
          pip install build twine
          
      - name: Build package
        run: |
          python -m build --no-isolation
          
      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > SHA256SUMS
          
      - name: Determine if prerelease
        id: prerelease
        run: |
          if [[ "${{ github.ref_name }}" == *"-rc"* ]] || [[ "${{ github.ref_name }}" == *"-alpha"* ]] || [[ "${{ github.ref_name }}" == *"-beta"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Publish to TestPyPI (prerelease)
        if: steps.prerelease.outputs.is_prerelease == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          
      - name: Publish to PyPI (release)
        if: steps.prerelease.outputs.is_prerelease == 'false'
        uses: pypa/gh-action-pypi-publish@release/v1
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            dist/SHA256SUMS
          draft: false
          prerelease: ${{ steps.prerelease.outputs.is_prerelease == 'true' }}
          generate_release_notes: true
          body: |
            ## What's Changed in ${{ github.ref_name }}
            
            This release includes updates to SS360 Secret Scanner.
            
            ### Installation
            
            ```bash
            pip install secret-scan-360==${{ github.ref_name }}
            ```
            
            ### Verification
            
            Verify the download using SHA256 checksums:
            ```bash
            sha256sum -c SHA256SUMS
            ```
            
            ### CLI Usage
            
            ```bash
            ss360 --help
            python -m ss360 --help
            ```