name: SS360 → Agents
on:
  push:
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SS360 scanner
        run: |
          pip install secret-scan-360  # or your local runner script
          ss360 scan --format json --output findings.json .
      - name: Post highs to Agents
        env:
          AGENTS_URL: ${{ secrets.AGENTS_URL }}     # e.g. https://agents.myvm:8080
        run: |
          jq -c '.findings[] | select(.severity|IN("high","critical"))' findings.json | \
          while read -r f; do
            repo="${GITHUB_REPOSITORY}"
            job_id="${GITHUB_RUN_ID}"
            id=$(echo "$f" | jq -r '.id')
            path=$(echo "$f" | jq -r '.file_path')
            det=$(echo "$f" | jq -r '.detector_id')
            sev=$(echo "$f" | jq -r '.severity')
            rec=$(echo "$f" | jq -r '.recommendation // empty')
            curl -s -X POST "$AGENTS_URL/events/ss360" -H 'Content-Type: application/json' \
              -d "{\"event\":\"finding.$sev\",\"repo\":\"$repo\",\"job_id\":\"$job_id\",\"finding_id\":\"$id\",\"file_path\":\"$path\",\"detector_id\":\"$det\",\"severity\":\"$sev\",\"recommendation\":\"$rec\"}"
          done

